from fastapi import APIRouter, HTTPException, Depends
from pydantic import BaseModel, EmailStr, validator
from sqlalchemy.orm import Session
from passlib.context import CryptContext
import os
import subprocess
from pathlib import Path

from apps.api.src.app.deps.auth import get_db
from libs.core.src.domains.auth.models import User
from libs.database.src.session import engine

router = APIRouter()
pwd_context = CryptContext(schemes=["bcrypt"], deprecated="auto")

class SetupConfig(BaseModel):
    botToken: str
    apiSecretKey: str
    databaseUrl: str
    gcpProjectId: str = ""
    adminEmail: EmailStr
    adminPassword: str

    @validator('botToken')
    def validate_bot_token(cls, v):
        if ':' not in v or len(v) < 20:
            raise ValueError('Invalid Telegram Bot Token format')
        return v

    @validator('apiSecretKey')
    def validate_secret_key(cls, v):
        if len(v) < 32:
            raise ValueError('API Secret Key must be at least 32 characters')
        return v

    @validator('databaseUrl')
    def validate_database_url(cls, v):
        if not v.startswith('postgresql://'):
            raise ValueError('Database URL must start with postgresql://')
        return v

    @validator('adminPassword')
    def validate_password(cls, v):
        if len(v) < 8:
            raise ValueError('Password must be at least 8 characters')
        return v


def check_if_setup_completed():
    """Check if setup has already been completed"""
    env_file = Path('/app/.env')
    if env_file.exists():
        return True
    
    # Also check if admin user exists
    try:
        from libs.database.src.session import SessionLocal
        db = SessionLocal()
        admin_exists = db.query(User).filter(User.role == 'admin').first()
        db.close()
        return admin_exists is not None
    except:
        return False


@router.post("/setup")
async def setup_system(config: SetupConfig, db: Session = Depends(get_db)):
    """
    Initial system setup endpoint.
    Creates .env file, runs migrations, creates admin user.
    """
    
    # Check if setup already completed
    if check_if_setup_completed():
        raise HTTPException(
            status_code=400,
            detail="Setup has already been completed. Contact administrator to reconfigure."
        )
    
    try:
        # 1. Create .env file
        env_content = f"""# Generated by Setup Wizard
DATABASE_URL={config.databaseUrl}
DATABASE_POOL_SIZE=5
DATABASE_MAX_OVERFLOW=10

REDIS_URL=redis://localhost:6379/0

BOT_TOKEN={config.botToken}
TELEGRAM_WEBHOOK_URL=https://your-domain.com/webhook
TELEGRAM_WEBHOOK_SECRET=auto-generated-secret

API_HOST=0.0.0.0
API_PORT=8000
API_SECRET_KEY={config.apiSecretKey}
API_CORS_ORIGINS=http://localhost:3000,http://localhost:8000

GOOGLE_CLOUD_PROJECT={config.gcpProjectId}
GCS_BUCKET_NAME={config.gcpProjectId}-uploads

ENVIRONMENT=production
LOG_LEVEL=INFO
TZ=Asia/Jerusalem
"""
        
        env_path = Path('/app/.env')
        env_path.write_text(env_content)
        
        # 2. Test database connection
        try:
            from sqlalchemy import create_engine, text
            test_engine = create_engine(config.databaseUrl)
            with test_engine.connect() as conn:
                conn.execute(text("SELECT 1"))
            test_engine.dispose()
        except Exception as e:
            raise HTTPException(
                status_code=400,
                detail=f"Database connection failed: {str(e)}"
            )
        
        # 3. Run database migrations
        try:
            alembic_ini = Path('/app/libs/database/alembic.ini')
            result = subprocess.run(
                ['alembic', '-c', str(alembic_ini), 'upgrade', 'head'],
                capture_output=True,
                text=True,
                timeout=60
            )
            if result.returncode != 0:
                raise Exception(f"Migration failed: {result.stderr}")
        except Exception as e:
            raise HTTPException(
                status_code=500,
                detail=f"Database migration failed: {str(e)}"
            )
        
        # 4. Create admin user
        hashed_password = pwd_context.hash(config.adminPassword)
        admin_user = User(
            email=config.adminEmail,
            hashed_password=hashed_password,
            full_name="System Administrator",
            role="admin",
            is_active=True
        )
        db.add(admin_user)
        db.commit()
        db.refresh(admin_user)
        
        # 5. Set setup completion flag
        setup_flag = Path('/app/.setup_completed')
        setup_flag.write_text('1')
        
        return {
            "success": True,
            "message": "System setup completed successfully",
            "admin_user_id": str(admin_user.id)
        }
        
    except HTTPException:
        raise
    except Exception as e:
        db.rollback()
        raise HTTPException(
            status_code=500,
            detail=f"Setup failed: {str(e)}"
        )


@router.get("/setup/status")
async def get_setup_status():
    """Check if system setup is required"""
    return {
        "setup_required": not check_if_setup_completed()
    }
